services:
  mindustry-server:
    build: .
    container_name: mindustry-server
    ports:
      - '6567:6567/tcp'
      - '6567:6567/udp'
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512M
    user: '1000:1000'
    volumes:
      # Конфиги + моды (всё из server/config)
      - ./server/config:/app/config
      # Логи наружу
      - ./server/logs:/app/logs
      # Сам jar наружу, чтобы можно было менять
      - ./server/server.jar:/app/server.jar
    tty: true
    stdin_open: true
    network_mode: bridge
