version: '3.8'

services:
  mindustry-server:
    build: .
    container_name: mindustry-server
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
      - "6868:6868"
    volumes:
      - ./server/config:/app/config
      - ./server/maps:/app/maps
      - ./server/mods:/app/mods
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512M
    # Ограничения ресурсов для слабого сервера
    deploy:
      resources:
        limits:
          memory: 600M
        reservations:
          memory: 512M